apiVersion: v1
kind: Service
metadata:
  name: spamdetector-service
spec:
  type: NodePort
  selector:
    app: spamdetector
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
